#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

routes:
  # - id: 1
  #   uri: /web1/*
  #   upstream:
  #     type: roundrobin
  #     nodes:
  #       - host: web1
  #         port: 80
  #         weight: 1

  # - id: 2
  #   uri: /web2/*
  #   upstream:
  #     type: roundrobin
  #     nodes:
  #       - host: web2
  #         port: 80
  #         weight: 1

  # - id: 3
  #   uri: /chat/message
  #   plugins:
  #     proxy-rewrite:
  #       uri: "/topics/chat.events"
  #   upstream:
  #     type: roundrobin
  #     nodes:
  #       - host: redpanda
  #         port: 8082
  #         weight: 1

  - id: 4
    uri: /webhook/livechat
    upstream:
      type: roundrobin
      nodes:
        - host: escalation-router
          port: 8003
          weight: 1

  - id: 5
    uri: /webhook/cpall
    upstream:
      type: roundrobin
      nodes:
        - host: redpanda-connect
          port: 4195
          weight: 1

#END
